// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS1JvzWIwQ_MalcP5FPnK3cuyotrJz_dc',
    appId: '1:279650897208:android:6b769aabb0ca447eae45cd',
    messagingSenderId: '279650897208',
    projectId: 'learning-mangament-app',
    storageBucket: 'learning-mangament-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDHOnKdw1WdAummbasNFTWxP8iUoLgHgQ',
    appId: '1:279650897208:ios:621933033af91493ae45cd',
    messagingSenderId: '279650897208',
    projectId: 'learning-mangament-app',
    storageBucket: 'learning-mangament-app.firebasestorage.app',
    iosBundleId: 'com.example.lms',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc1dyjyxyLCabC0jBsKkclG2sgJ1kCNiQ',
    appId: '1:279650897208:web:599e2adce2aa163bae45cd',
    messagingSenderId: '279650897208',
    projectId: 'learning-mangament-app',
    authDomain: 'learning-mangament-app.firebaseapp.com',
    storageBucket: 'learning-mangament-app.firebasestorage.app',
    measurementId: 'G-1623VFZ9TT',
  );

}